/**
 * Service de gestion des téléconsultations
 * Gestion complète du cycle de vie: création, session WebRTC, événements, documents, notes
 */

import { supabase } from '@/integrations/supabase/client';
import type {
  Teleconsultation,
  TeleconsultationWithRelations,
  TeleconsultationSession,
  TeleconsultationEvent,
  TeleconsultationDocument,
  TeleconsultationNote,
  TeleconsultationRecording,
  CreateTeleconsultationRequest,
  UpdateTeleconsultationRequest,
  JoinTeleconsultationRequest,
  TeleconsultationAccess,
  ConnectionQualityUpdate,
  ShareDocumentRequest,
  CreateNoteRequest,
  StartRecordingRequest,
  TeleconsultationStatus,
  EventType,
  ActorType,
  ParticipantType,
  NetworkStats,
  DeviceInfo,
} from '@/types/teleconsultation';

// ============================================================================
// TELECONSULTATION CRUD
// ============================================================================

/**
 * Créer une nouvelle téléconsultation
 * Génère automatiquement: room_token, links, expiration (via trigger DB)
 */
export async function createTeleconsultation(
  request: CreateTeleconsultationRequest
): Promise<Teleconsultation> {
  const { data: userData } = await supabase.auth.getUser();
  if (!userData.user) throw new Error('User not authenticated');

  // Generate room token (32 bytes random)
  const roomToken = Array.from(crypto.getRandomValues(new Uint8Array(32)))
    .map(b => b.toString(16).padStart(2, '0'))
    .join('');

  // Calculate expiration (24h after scheduled start)
  const scheduledDate = new Date(request.scheduled_start);
  const expiresAt = new Date(scheduledDate.getTime() + 24 * 60 * 60 * 1000);

  const teleconsultationData = {
    appointment_id: request.appointment_id,
    patient_id: request.patient_id,
    practitioner_id: request.practitioner_id,
    scheduled_start: request.scheduled_start,
    consultation_reason: request.consultation_reason || null,
    chief_complaint: request.chief_complaint || null,
    status: 'scheduled' as TeleconsultationStatus,
    technical_check_done: false,
    room_token: roomToken,
    room_expires_at: expiresAt.toISOString(),
    settings: {
      video_enabled: true,
      audio_enabled: true,
      screen_share_enabled: false,
      recording_enabled: false,
      quality: 'auto',
      ...request.settings,
    },
    created_by: userData.user.id,
  };

  const { data, error } = await supabase
    .from('teleconsultations')
    .insert(teleconsultationData)
    .select('*')
    .single();

  if (error) {
    console.error('Error creating teleconsultation:', error);

    // Erreur spécifique: table n'existe pas
    if (error.code === 'PGRST205') {
      throw new Error(
        'Les tables de téléconsultation n\'existent pas dans la base de données. ' +
        'Veuillez exécuter le fichier de migration SQL : ' +
        'supabase/migrations/EXECUTE_THIS_FIRST_teleconsultation_essential.sql ' +
        'dans votre Supabase SQL Editor. Consultez le fichier GUIDE_MIGRATION_TELECONSULTATION.md pour les instructions.'
      );
    }

    throw new Error(`Failed to create teleconsultation: ${error.message}`);
  }

  // If links weren't generated by trigger, generate them manually
  if (!data.patient_link || !data.practitioner_link) {
    const baseUrl = `${window.location.origin}/visio/`;
    const patientLink = `${baseUrl}patient/${data.id}?token=${roomToken}`;
    const practitionerLink = `${baseUrl}practitioner/${data.id}?token=${roomToken}`;

    const { data: updatedData, error: updateError } = await supabase
      .from('teleconsultations')
      .update({
        patient_link: patientLink,
        practitioner_link: practitionerLink,
      })
      .eq('id', data.id)
      .select('*')
      .single();

    if (updateError) {
      console.error('Error updating teleconsultation links:', updateError);
      throw new Error(`Failed to update teleconsultation links: ${updateError.message}`);
    }

    // Log creation event
    await logEvent({
      teleconsultation_id: updatedData.id,
      event_type: 'session_started',
      actor_type: 'system',
      event_data: { created_by: userData.user.id },
      severity: 'info',
    });

    return updatedData as Teleconsultation;
  }

  // Log creation event
  await logEvent({
    teleconsultation_id: data.id,
    event_type: 'session_started',
    actor_type: 'system',
    event_data: { created_by: userData.user.id },
    severity: 'info',
  });

  return data as Teleconsultation;
}

/**
 * Récupérer une téléconsultation par ID
 */
export async function getTeleconsultation(id: string): Promise<Teleconsultation | null> {
  const { data, error } = await supabase
    .from('teleconsultations')
    .select('*')
    .eq('id', id)
    .is('deleted_at', null)
    .single();

  if (error) {
    if (error.code === 'PGRST116') return null; // Not found
    if (error.code === 'PGRST205') return null; // Table doesn't exist - silently return null
    console.error('Error fetching teleconsultation:', error);
    throw new Error(`Failed to fetch teleconsultation: ${error.message}`);
  }

  return data as Teleconsultation;
}

/**
 * Récupérer une téléconsultation avec toutes ses relations
 */
export async function getTeleconsultationWithRelations(
  id: string
): Promise<TeleconsultationWithRelations | null> {
  const teleconsultation = await getTeleconsultation(id);
  if (!teleconsultation) return null;

  // Fetch related data in parallel
  const [sessionsResult, eventsResult, documentsResult, notesResult, recordingResult] = await Promise.all([
    supabase
      .from('teleconsultation_sessions')
      .select('*')
      .eq('teleconsultation_id', id)
      .order('created_at', { ascending: false }),
    supabase
      .from('teleconsultation_events')
      .select('*')
      .eq('teleconsultation_id', id)
      .order('occurred_at', { ascending: false })
      .limit(50),
    supabase
      .from('teleconsultation_documents')
      .select('*')
      .eq('teleconsultation_id', id)
      .order('shared_at', { ascending: false }),
    supabase
      .from('teleconsultation_notes')
      .select('*')
      .eq('teleconsultation_id', id)
      .is('deleted_at', null)
      .order('created_at', { ascending: false }),
    supabase
      .from('teleconsultation_recordings')
      .select('*')
      .eq('teleconsultation_id', id)
      .is('deleted_at', null)
      .single(),
  ]);

  return {
    ...teleconsultation,
    sessions: (sessionsResult.data || []) as TeleconsultationSession[],
    events: (eventsResult.data || []) as TeleconsultationEvent[],
    documents: (documentsResult.data || []) as TeleconsultationDocument[],
    notes: (notesResult.data || []) as TeleconsultationNote[],
    recording: recordingResult.data ? (recordingResult.data as TeleconsultationRecording) : undefined,
  };
}

/**
 * Récupérer une téléconsultation par appointment_id
 */
export async function getTeleconsultationByAppointment(
  appointmentId: string
): Promise<Teleconsultation | null> {
  const { data, error } = await supabase
    .from('teleconsultations')
    .select('*')
    .eq('appointment_id', appointmentId)
    .is('deleted_at', null)
    .single();

  if (error) {
    if (error.code === 'PGRST116') return null; // Not found
    if (error.code === 'PGRST205') return null; // Table doesn't exist - silently return null
    console.error('Error fetching teleconsultation by appointment:', error);
    throw new Error(`Failed to fetch teleconsultation: ${error.message}`);
  }

  return data as Teleconsultation;
}

/**
 * Récupérer toutes les téléconsultations d'un praticien
 */
export async function getTeleconsultations(): Promise<TeleconsultationWithRelations[]> {
  try {
    const { data: userData, error: authError } = await supabase.auth.getUser();

    if (authError || !userData?.user) {
      console.error('Auth error in getTeleconsultations:', authError);
      return []; // Return empty array instead of throwing
    }

    // Get practitioner ID from user
    const { data: practitioner, error: practitionerError } = await supabase
      .from('practitioners')
      .select('id')
      .eq('user_id', userData.user.id)
      .maybeSingle(); // Use maybeSingle() instead of single() to avoid error if not found

    if (practitionerError) {
      console.error('Error fetching practitioner:', practitionerError);
      return []; // Return empty array if practitioner fetch fails
    }

    if (!practitioner) {
      console.warn('No practitioner found for user:', userData.user.id);
      return []; // Return empty array if no practitioner
    }

    const { data, error } = await supabase
      .from('teleconsultations')
      .select(`
        *,
        patient:patients!patient_id (
          id,
          first_name,
          last_name,
          date_of_birth,
          phone,
          email
        ),
        practitioner:practitioners!practitioner_id (
          id,
          first_name,
          last_name,
          title,
          specialty
        ),
        appointment:appointments!appointment_id (
          id,
          start_time,
          end_time
        )
      `)
      .eq('practitioner_id', practitioner.id)
      .is('deleted_at', null)
      .order('scheduled_start', { ascending: false });

    if (error) {
      console.error('Error fetching teleconsultations:', error);
      return []; // Return empty array on error instead of throwing
    }

    return (data || []) as unknown as TeleconsultationWithRelations[];
  } catch (error) {
    console.error('Unexpected error in getTeleconsultations:', error);
    return []; // Always return empty array on any error
  }
}

/**
 * Mettre à jour une téléconsultation
 */
export async function updateTeleconsultation(
  id: string,
  updates: UpdateTeleconsultationRequest
): Promise<Teleconsultation> {
  const { data: userData } = await supabase.auth.getUser();

  const updateData: Record<string, unknown> = {
    ...updates,
    updated_at: new Date().toISOString(),
    updated_by: userData.user?.id,
  };

  const { data, error } = await supabase
    .from('teleconsultations')
    .update(updateData)
    .eq('id', id)
    .select('*')
    .single();

  if (error) {
    console.error('Error updating teleconsultation:', error);
    throw new Error(`Failed to update teleconsultation: ${error.message}`);
  }

  // Log status change if status was updated
  if (updates.status) {
    await logEvent({
      teleconsultation_id: id,
      event_type: `session_${updates.status}` as EventType,
      actor_type: 'practitioner',
      actor_id: userData.user?.id,
      event_data: { status: updates.status },
      severity: 'info',
    });
  }

  return data as Teleconsultation;
}

/**
 * Supprimer une téléconsultation (soft delete)
 */
export async function deleteTeleconsultation(id: string): Promise<void> {
  const { data: userData } = await supabase.auth.getUser();

  const { error } = await supabase
    .from('teleconsultations')
    .update({
      deleted_at: new Date().toISOString(),
      deleted_by: userData.user?.id,
      status: 'cancelled',
    })
    .eq('id', id);

  if (error) {
    console.error('Error deleting teleconsultation:', error);
    throw new Error(`Failed to delete teleconsultation: ${error.message}`);
  }

  await logEvent({
    teleconsultation_id: id,
    event_type: 'session_ended',
    actor_type: 'practitioner',
    actor_id: userData.user?.id,
    event_data: { reason: 'deleted' },
    severity: 'warning',
  });
}

// ============================================================================
// ACCESS & VALIDATION
// ============================================================================

/**
 * Valider l'accès à une téléconsultation via token
 */
export async function validateTeleconsultationAccess(
  teleconsultationId: string,
  token: string,
  participantType: ParticipantType
): Promise<TeleconsultationAccess> {
  const teleconsultation = await getTeleconsultation(teleconsultationId);

  if (!teleconsultation) {
    return {
      isValid: false,
      error: 'Téléconsultation not found',
    };
  }

  // Check token match
  if (teleconsultation.room_token !== token) {
    await logEvent({
      teleconsultation_id: teleconsultationId,
      event_type: 'unauthorized_access_attempt',
      actor_type: participantType,
      event_data: { reason: 'invalid_token' },
      severity: 'critical',
    });

    return {
      isValid: false,
      error: 'Invalid access token',
    };
  }

  // Check expiration
  const now = new Date();
  const expiresAt = new Date(teleconsultation.room_expires_at);
  if (now > expiresAt) {
    await logEvent({
      teleconsultation_id: teleconsultationId,
      event_type: 'link_expired',
      actor_type: participantType,
      event_data: { expires_at: teleconsultation.room_expires_at },
      severity: 'warning',
    });

    return {
      isValid: false,
      error: 'Access link has expired',
    };
  }

  // Check if already completed/cancelled
  if (['completed', 'cancelled', 'failed'].includes(teleconsultation.status)) {
    return {
      isValid: false,
      error: `Teleconsultation is ${teleconsultation.status}`,
    };
  }

  return {
    isValid: true,
    teleconsultation,
    participantType,
  };
}

// ============================================================================
// SESSION MANAGEMENT
// ============================================================================

/**
 * Créer une session de connexion
 */
export async function createSession(request: JoinTeleconsultationRequest): Promise<TeleconsultationSession> {
  const { data: userData } = await supabase.auth.getUser();

  // Validate access first
  const access = await validateTeleconsultationAccess(
    request.teleconsultation_id,
    request.token,
    request.participant_type
  );

  if (!access.isValid) {
    throw new Error(access.error || 'Access denied');
  }

  // Create session
  const sessionData = {
    teleconsultation_id: request.teleconsultation_id,
    participant_type: request.participant_type,
    user_id: userData.user?.id,
    peer_id: `${request.participant_type}_${Date.now()}`,
    connection_id: `conn_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    status: 'connecting' as const,
    device_info: request.device_info,
    last_heartbeat: new Date().toISOString(),
  };

  const { data, error } = await supabase
    .from('teleconsultation_sessions')
    .insert(sessionData)
    .select('*')
    .single();

  if (error) {
    console.error('Error creating session:', error);
    throw new Error(`Failed to create session: ${error.message}`);
  }

  // Log join event
  await logEvent({
    teleconsultation_id: request.teleconsultation_id,
    session_id: data.id,
    event_type: request.participant_type === 'patient' ? 'patient_joined' : 'practitioner_joined',
    actor_type: request.participant_type,
    actor_id: userData.user?.id,
    event_data: {
      device_info: request.device_info,
      session_id: data.id,
    },
    severity: 'info',
  });

  return data as TeleconsultationSession;
}

/**
 * Mettre à jour une session
 */
export async function updateSession(
  sessionId: string,
  updates: {
    status?: TeleconsultationSession['status'];
    connected_at?: string;
    disconnected_at?: string;
    connection_quality?: TeleconsultationSession['connection_quality'];
    network_stats?: NetworkStats;
  }
): Promise<TeleconsultationSession> {
  const { data, error } = await supabase
    .from('teleconsultation_sessions')
    .update({
      ...updates,
      updated_at: new Date().toISOString(),
      last_heartbeat: new Date().toISOString(),
    })
    .eq('id', sessionId)
    .select('*')
    .single();

  if (error) {
    console.error('Error updating session:', error);
    throw new Error(`Failed to update session: ${error.message}`);
  }

  return data as TeleconsultationSession;
}

/**
 * Mettre à jour la qualité de connexion
 */
export async function updateConnectionQuality(update: ConnectionQualityUpdate): Promise<void> {
  await updateSession(update.session_id, {
    connection_quality: update.quality,
    network_stats: update.network_stats,
  });

  // Log if quality is degraded
  if (['poor', 'critical'].includes(update.quality)) {
    const session = await supabase
      .from('teleconsultation_sessions')
      .select('teleconsultation_id, participant_type')
      .eq('id', update.session_id)
      .single();

    if (session.data) {
      await logEvent({
        teleconsultation_id: session.data.teleconsultation_id,
        session_id: update.session_id,
        event_type: 'quality_degraded',
        actor_type: session.data.participant_type as ActorType,
        event_data: {
          quality: update.quality,
          network_stats: update.network_stats,
        },
        severity: update.quality === 'critical' ? 'critical' : 'warning',
      });
    }
  }
}

/**
 * Heartbeat pour maintenir la session active
 */
export async function sessionHeartbeat(sessionId: string): Promise<void> {
  const { error } = await supabase
    .from('teleconsultation_sessions')
    .update({
      last_heartbeat: new Date().toISOString(),
    })
    .eq('id', sessionId);

  if (error) {
    console.error('Error updating heartbeat:', error);
  }
}

// ============================================================================
// EVENTS & LOGGING
// ============================================================================

/**
 * Logger un événement
 */
export async function logEvent(event: {
  teleconsultation_id: string;
  session_id?: string;
  event_type: EventType;
  actor_type: ActorType;
  actor_id?: string;
  event_data?: Record<string, unknown>;
  severity?: 'info' | 'warning' | 'error' | 'critical';
}): Promise<void> {
  const { error } = await supabase.from('teleconsultation_events').insert({
    teleconsultation_id: event.teleconsultation_id,
    session_id: event.session_id || null,
    event_type: event.event_type,
    actor_type: event.actor_type,
    actor_id: event.actor_id || null,
    event_data: event.event_data || {},
    severity: event.severity || 'info',
    occurred_at: new Date().toISOString(),
  });

  if (error) {
    console.error('Error logging event:', error);
    // Don't throw - logging should not break main flow
  }
}

/**
 * Récupérer les événements d'une téléconsultation
 */
export async function getEvents(
  teleconsultationId: string,
  options?: {
    limit?: number;
    offset?: number;
    eventTypes?: EventType[];
  }
): Promise<TeleconsultationEvent[]> {
  let query = supabase
    .from('teleconsultation_events')
    .select('*')
    .eq('teleconsultation_id', teleconsultationId)
    .order('occurred_at', { ascending: false });

  if (options?.eventTypes && options.eventTypes.length > 0) {
    query = query.in('event_type', options.eventTypes);
  }

  if (options?.limit) {
    query = query.limit(options.limit);
  }

  if (options?.offset) {
    query = query.range(options.offset, options.offset + (options.limit || 50) - 1);
  }

  const { data, error } = await query;

  if (error) {
    console.error('Error fetching events:', error);
    throw new Error(`Failed to fetch events: ${error.message}`);
  }

  return data as TeleconsultationEvent[];
}

// ============================================================================
// BILLING INTEGRATION
// ============================================================================

/**
 * Créer une facture automatiquement pour une téléconsultation terminée
 */
export async function createInvoiceForTeleconsultation(
  teleconsultationId: string
): Promise<any> {
  // Récupérer la téléconsultation avec les détails
  const { data: teleconsultation, error: tcError } = await supabase
    .from('teleconsultations')
    .select('*, patient_id, practitioner_id, appointment_id, consultation_id')
    .eq('id', teleconsultationId)
    .single();

  if (tcError || !teleconsultation) {
    throw new Error('Teleconsultation not found');
  }

  // Vérifier si une facture existe déjà
  const { data: existingInvoice } = await supabase
    .from('invoices')
    .select('id')
    .eq('metadata->>teleconsultation_id', teleconsultationId)
    .single();

  if (existingInvoice) {
    console.log('Invoice already exists for this teleconsultation');
    return existingInvoice;
  }

  // Calculer le montant (à adapter selon votre tarification)
  const teleconsultationRate = 25.0; // 25€ par défaut pour une téléconsultation
  const subtotal = teleconsultationRate;
  const taxRate = 0.0; // Pas de TVA pour les actes médicaux en France
  const taxAmount = subtotal * taxRate;
  const totalAmount = subtotal + taxAmount;

  // Générer le numéro de facture
  const invoiceNumber = `TC-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;

  // Créer la facture
  const { data: invoice, error: invError } = await supabase
    .from('invoices')
    .insert({
      invoice_number: invoiceNumber,
      patient_id: teleconsultation.patient_id,
      practitioner_id: teleconsultation.practitioner_id,
      appointment_id: teleconsultation.appointment_id,
      consultation_id: teleconsultation.consultation_id,
      status: 'issued', // Facture émise automatiquement
      issue_date: new Date().toISOString().split('T')[0],
      due_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 30 jours
      subtotal,
      tax_amount: taxAmount,
      discount_amount: 0,
      total_amount: totalAmount,
      paid_amount: 0,
      currency: 'EUR',
      notes: 'Téléconsultation médicale à distance',
      metadata: {
        teleconsultation_id: teleconsultationId,
        consultation_type: 'teleconsultation',
        duration_minutes: teleconsultation.duration_minutes,
      },
    })
    .select()
    .single();

  if (invError) {
    console.error('Error creating invoice:', invError);
    throw new Error(`Failed to create invoice: ${invError.message}`);
  }

  // Créer les lignes de facture
  const { error: itemError } = await supabase
    .from('invoice_items')
    .insert({
      invoice_id: invoice.id,
      description: 'Téléconsultation médicale',
      quantity: 1,
      unit_price: teleconsultationRate,
      tax_rate: taxRate,
      amount: totalAmount,
      sort_order: 0,
    });

  if (itemError) {
    console.error('Error creating invoice item:', itemError);
  }

  // Logger l'événement
  await logEvent({
    teleconsultation_id: teleconsultationId,
    event_type: 'invoice_created',
    actor_type: 'system',
    event_data: {
      invoice_id: invoice.id,
      invoice_number: invoiceNumber,
      total_amount: totalAmount,
    },
    severity: 'info',
  });

  return invoice;
}

// ============================================================================
// DOCUMENTS SHARING
// ============================================================================

/**
 * Partager un document pendant la téléconsultation
 */
export async function shareDocument(request: ShareDocumentRequest): Promise<TeleconsultationDocument> {
  const documentShareData = {
    teleconsultation_id: request.teleconsultation_id,
    document_id: request.document_id,
    shared_by: request.shared_by,
    shared_by_id: request.shared_by_id,
    shared_at: new Date().toISOString(),
    share_type: request.share_type || 'during_consultation',
    visible_to_patient: request.visible_to_patient !== undefined ? request.visible_to_patient : true,
    visible_to_practitioner: request.visible_to_practitioner !== undefined ? request.visible_to_practitioner : true,
    viewed_by_patient: false,
    viewed_by_practitioner: request.shared_by === 'practitioner',
  };

  const { data, error } = await supabase
    .from('teleconsultation_documents')
    .insert(documentShareData)
    .select('*')
    .single();

  if (error) {
    console.error('Error sharing document:', error);
    throw new Error(`Failed to share document: ${error.message}`);
  }

  // Log document share event
  await logEvent({
    teleconsultation_id: request.teleconsultation_id,
    event_type: 'document_shared',
    actor_type: request.shared_by,
    actor_id: request.shared_by_id,
    event_data: {
      document_id: request.document_id,
    },
    severity: 'info',
  });

  return data as TeleconsultationDocument;
}

/**
 * Récupérer tous les documents partagés d'une téléconsultation
 */
export async function getDocuments(teleconsultationId: string): Promise<TeleconsultationDocument[]> {
  const { data, error} = await supabase
    .from('teleconsultation_documents')
    .select(`
      *,
      document:document_id (
        id,
        title,
        file_path,
        file_type,
        file_size,
        url
      )
    `)
    .eq('teleconsultation_id', teleconsultationId)
    .order('shared_at', { ascending: true });

  if (error) {
    console.error('Error fetching documents:', error);
    throw new Error(`Failed to fetch documents: ${error.message}`);
  }

  return data as TeleconsultationDocument[];
}

/**
 * Marquer un document comme vu
 */
export async function markDocumentAsViewed(
  documentShareId: string,
  viewedBy: ParticipantType
): Promise<void> {
  const updateField =
    viewedBy === 'patient' ? 'viewed_by_patient' : 'viewed_by_practitioner';
  const viewedAtField =
    viewedBy === 'patient' ? 'patient_viewed_at' : 'practitioner_viewed_at';

  const { error } = await supabase
    .from('teleconsultation_documents')
    .update({
      [updateField]: true,
      [viewedAtField]: new Date().toISOString(),
      status: 'viewed',
    })
    .eq('id', documentShareId);

  if (error) {
    console.error('Error marking document as viewed:', error);
    throw new Error(`Failed to mark document as viewed: ${error.message}`);
  }

  // Log view event
  const doc = await supabase
    .from('teleconsultation_documents')
    .select('teleconsultation_id, document_id')
    .eq('id', documentShareId)
    .single();

  if (doc.data) {
    await logEvent({
      teleconsultation_id: doc.data.teleconsultation_id,
      event_type: 'document_viewed',
      actor_type: viewedBy,
      event_data: {
        document_id: doc.data.document_id,
        document_share_id: documentShareId,
      },
      severity: 'info',
    });
  }
}

// ============================================================================
// NOTES
// ============================================================================

/**
 * Créer une note pendant la téléconsultation
 */
export async function createNote(request: CreateNoteRequest): Promise<TeleconsultationNote> {
  const { data: userData } = await supabase.auth.getUser();
  if (!userData.user) throw new Error('User not authenticated');

  // Get practitioner_id from user
  const { data: practitioner } = await supabase
    .from('practitioners')
    .select('id')
    .eq('user_id', userData.user.id)
    .single();

  if (!practitioner) throw new Error('Practitioner not found');

  const noteData = {
    teleconsultation_id: request.teleconsultation_id,
    practitioner_id: practitioner.id,
    content: request.content,
    note_type: request.note_type || 'general',
    tags: request.tags || [],
    icd10_codes: request.icd10_codes || [],
    is_private: request.is_private ?? true,
  };

  const { data, error } = await supabase
    .from('teleconsultation_notes')
    .insert(noteData)
    .select('*')
    .single();

  if (error) {
    console.error('Error creating note:', error);
    throw new Error(`Failed to create note: ${error.message}`);
  }

  // Log note creation
  await logEvent({
    teleconsultation_id: request.teleconsultation_id,
    event_type: 'note_added',
    actor_type: 'practitioner',
    actor_id: userData.user.id,
    event_data: {
      note_id: data.id,
      note_type: request.note_type,
    },
    severity: 'info',
  });

  return data as TeleconsultationNote;
}

/**
 * Récupérer les notes d'une téléconsultation
 */
export async function getNotes(teleconsultationId: string): Promise<TeleconsultationNote[]> {
  const { data, error } = await supabase
    .from('teleconsultation_notes')
    .select('*')
    .eq('teleconsultation_id', teleconsultationId)
    .is('deleted_at', null)
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Error fetching notes:', error);
    throw new Error(`Failed to fetch notes: ${error.message}`);
  }

  return data as TeleconsultationNote[];
}

/**
 * Supprimer une note (soft delete)
 */
export async function deleteNote(noteId: string): Promise<void> {
  const { data: userData } = await supabase.auth.getUser();

  const { error } = await supabase
    .from('teleconsultation_notes')
    .update({
      deleted_at: new Date().toISOString(),
      deleted_by: userData.user?.id,
    })
    .eq('id', noteId);

  if (error) {
    console.error('Error deleting note:', error);
    throw new Error(`Failed to delete note: ${error.message}`);
  }
}

// ============================================================================
// RECORDING
// ============================================================================

/**
 * Démarrer un enregistrement
 */
export async function startRecording(request: StartRecordingRequest): Promise<TeleconsultationRecording> {
  const { data: userData } = await supabase.auth.getUser();
  if (!userData.user) throw new Error('User not authenticated');

  const recordingData = {
    teleconsultation_id: request.teleconsultation_id,
    status: 'requested' as const,
    consent_data: request.consent_data,
    started_at: new Date().toISOString(),
    expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 days
    created_by: userData.user.id,
  };

  const { data, error } = await supabase
    .from('teleconsultation_recordings')
    .insert(recordingData)
    .select('*')
    .single();

  if (error) {
    console.error('Error starting recording:', error);
    throw new Error(`Failed to start recording: ${error.message}`);
  }

  return data as TeleconsultationRecording;
}

/**
 * Mettre à jour un enregistrement
 */
export async function updateRecording(
  recordingId: string,
  updates: {
    status?: TeleconsultationRecording['status'];
    storage_path?: string;
    file_size_bytes?: number;
    duration_seconds?: number;
    completed_at?: string;
    processing_error?: string;
  }
): Promise<TeleconsultationRecording> {
  const { data, error } = await supabase
    .from('teleconsultation_recordings')
    .update({
      ...updates,
      updated_at: new Date().toISOString(),
    })
    .eq('id', recordingId)
    .select('*')
    .single();

  if (error) {
    console.error('Error updating recording:', error);
    throw new Error(`Failed to update recording: ${error.message}`);
  }

  return data as TeleconsultationRecording;
}
