/**
 * Service de gestion des téléconsultations
 * Gestion complète du cycle de vie: création, session WebRTC, événements, documents, notes
 */

import { supabase } from '@/integrations/supabase/client';
import { mockTeleconsultations } from '@/data/mockData';
import type {
  Teleconsultation,
  TeleconsultationWithRelations,
  TeleconsultationSession,
  TeleconsultationEvent,
  TeleconsultationDocument,
  TeleconsultationNote,
  TeleconsultationRecording,
  CreateTeleconsultationRequest,
  UpdateTeleconsultationRequest,
  JoinTeleconsultationRequest,
  TeleconsultationAccess,
  ConnectionQualityUpdate,
  ShareDocumentRequest,
  CreateNoteRequest,
  StartRecordingRequest,
  TeleconsultationStatus,
  EventType,
  ActorType,
  ParticipantType,
  NetworkStats,
  DeviceInfo,
} from '@/types/teleconsultation';

// ============================================================================
// TELECONSULTATION CRUD
// ============================================================================

/**
 * Créer une nouvelle téléconsultation
 * Génère automatiquement: room_token, links, expiration (via trigger DB)
 */
export async function createTeleconsultation(
  request: CreateTeleconsultationRequest
): Promise<Teleconsultation> {
  const { data: userData } = await supabase.auth.getUser();
  if (!userData.user) throw new Error('User not authenticated');

  // Generate room token (32 bytes random)
  const roomToken = Array.from(crypto.getRandomValues(new Uint8Array(32)))
    .map(b => b.toString(16).padStart(2, '0'))
    .join('');

  // Calculate expiration (24h after scheduled start)
  const scheduledDate = new Date(request.scheduled_start);
  const expiresAt = new Date(scheduledDate.getTime() + 24 * 60 * 60 * 1000);

  const teleconsultationData = {
    appointment_id: request.appointment_id,
    patient_id: request.patient_id,
    practitioner_id: request.practitioner_id,
    scheduled_start: request.scheduled_start,
    consultation_reason: request.consultation_reason || null,
    chief_complaint: request.chief_complaint || null,
    status: 'scheduled' as TeleconsultationStatus,
    technical_check_done: false,
    room_token: roomToken,
    room_expires_at: expiresAt.toISOString(),
    settings: {
      video_enabled: true,
      audio_enabled: true,
      screen_share_enabled: false,
      recording_enabled: false,
      quality: 'auto',
      ...request.settings,
    },
    created_by: userData.user.id,
  };

  const { data, error } = await supabase
    .from('teleconsultations')
    .insert(teleconsultationData)
    .select('*')
    .single();

  if (error) {
    console.error('Error creating teleconsultation:', error);

    // Erreur spécifique: table n'existe pas
    if (error.code === 'PGRST205') {
      throw new Error(
        'Les tables de téléconsultation n\'existent pas dans la base de données. ' +
        'Veuillez exécuter le fichier de migration SQL : ' +
        'supabase/migrations/EXECUTE_THIS_FIRST_teleconsultation_essential.sql ' +
        'dans votre Supabase SQL Editor. Consultez le fichier GUIDE_MIGRATION_TELECONSULTATION.md pour les instructions.'
      );
    }

    throw new Error(`Failed to create teleconsultation: ${error.message}`);
  }

  // If links weren't generated by trigger, generate them manually
  if (!data.patient_link || !data.practitioner_link) {
    const baseUrl = `${window.location.origin}/visio/`;
    const patientLink = `${baseUrl}patient/${data.id}?token=${roomToken}`;
    const practitionerLink = `${baseUrl}practitioner/${data.id}?token=${roomToken}`;

    const { data: updatedData, error: updateError } = await supabase
      .from('teleconsultations')
      .update({
        patient_link: patientLink,
        practitioner_link: practitionerLink,
      })
      .eq('id', data.id)
      .select('*')
      .single();

    if (updateError) {
      console.error('Error updating teleconsultation links:', updateError);
      throw new Error(`Failed to update teleconsultation links: ${updateError.message}`);
    }

    // Log creation event
    await logEvent({
      teleconsultation_id: updatedData.id,
      event_type: 'session_started',
      actor_type: 'system',
      event_data: { created_by: userData.user.id },
      severity: 'info',
    });

    return updatedData as Teleconsultation;
  }

  // Log creation event
  await logEvent({
    teleconsultation_id: data.id,
    event_type: 'session_started',
    actor_type: 'system',
    event_data: { created_by: userData.user.id },
    severity: 'info',
  });

  return data as Teleconsultation;
}

/**
 * Récupérer une téléconsultation par ID
 */
export async function getTeleconsultation(id: string): Promise<Teleconsultation | null> {
  try {
    const { data, error } = await supabase
      .from('teleconsultations')
      .select('*')
      .eq('id', id)
      .is('deleted_at', null)
      .single();

    if (error) {
      if (error.code === 'PGRST116') return null; // Not found
      if (error.code === 'PGRST205') {
        // Table doesn't exist - try mock fallback
        const mock = mockTeleconsultations.find((tc) => tc.id === id);
        return mock || null;
      }
      console.warn('[Teleconsultation] Error fetching by id, trying mock:', error.message);
      const mock = mockTeleconsultations.find((tc) => tc.id === id);
      return mock || null;
    }

    return data as Teleconsultation;
  } catch {
    const mock = mockTeleconsultations.find((tc) => tc.id === id);
    return mock || null;
  }
}

/**
 * Récupérer une téléconsultation avec toutes ses relations
 */
export async function getTeleconsultationWithRelations(
  id: string
): Promise<TeleconsultationWithRelations | null> {
  const teleconsultation = await getTeleconsultation(id);
  if (!teleconsultation) return null;

  try {
    // Fetch related data in parallel
    const [sessionsResult, eventsResult, documentsResult, notesResult, recordingResult] = await Promise.all([
      supabase
        .from('teleconsultation_sessions')
        .select('*')
        .eq('teleconsultation_id', id)
        .order('created_at', { ascending: false }),
      supabase
        .from('teleconsultation_events')
        .select('*')
        .eq('teleconsultation_id', id)
        .order('occurred_at', { ascending: false })
        .limit(50),
      supabase
        .from('teleconsultation_documents')
        .select('*')
        .eq('teleconsultation_id', id)
        .order('shared_at', { ascending: false }),
      supabase
        .from('teleconsultation_notes')
        .select('*')
        .eq('teleconsultation_id', id)
        .is('deleted_at', null)
        .order('created_at', { ascending: false }),
      supabase
        .from('teleconsultation_recordings')
        .select('*')
        .eq('teleconsultation_id', id)
        .is('deleted_at', null)
        .single(),
    ]);

    return {
      ...teleconsultation,
      sessions: (sessionsResult.data || []) as TeleconsultationSession[],
      events: (eventsResult.data || []) as TeleconsultationEvent[],
      documents: (documentsResult.data || []) as TeleconsultationDocument[],
      notes: (notesResult.data || []) as TeleconsultationNote[],
      recording: recordingResult.data ? (recordingResult.data as TeleconsultationRecording) : undefined,
    };
  } catch {
    // Fallback: return teleconsultation with mock relations from mockTeleconsultations
    const mock = mockTeleconsultations.find((tc) => tc.id === id);
    if (mock) return mock;

    return {
      ...teleconsultation,
      sessions: [],
      events: [],
      documents: [],
      notes: [],
    };
  }
}

/**
 * Récupérer une téléconsultation par appointment_id
 */
export async function getTeleconsultationByAppointment(
  appointmentId: string
): Promise<Teleconsultation | null> {
  try {
    const { data, error } = await supabase
      .from('teleconsultations')
      .select('*')
      .eq('appointment_id', appointmentId)
      .is('deleted_at', null)
      .single();

    if (error) {
      if (error.code === 'PGRST116') return null;
      if (error.code === 'PGRST205') return null;
      console.warn('[Teleconsultation] Error fetching by appointment:', error.message);
      return null;
    }

    return data as Teleconsultation;
  } catch {
    console.warn('[Teleconsultation] Unexpected error fetching by appointment');
    return null;
  }
}

/**
 * Récupérer toutes les téléconsultations d'un praticien
 */
export async function getTeleconsultations(): Promise<TeleconsultationWithRelations[]> {
  try {
    const { data: userData, error: authError } = await supabase.auth.getUser();

    if (authError || !userData?.user) {
      console.warn('[Teleconsultation] Auth error, using mock data:', authError?.message);
      return mockTeleconsultations;
    }

    // Get practitioner ID from user
    const { data: practitioner, error: practitionerError } = await supabase
      .from('practitioners')
      .select('id')
      .eq('user_id', userData.user.id)
      .maybeSingle();

    if (practitionerError) {
      console.warn('[Teleconsultation] Practitioner fetch error, using mock data:', practitionerError.message);
      return mockTeleconsultations;
    }

    if (!practitioner) {
      console.warn('[Teleconsultation] No practitioner found, using mock data');
      return mockTeleconsultations;
    }

    const { data, error } = await supabase
      .from('teleconsultations')
      .select(`
        *,
        patient:patients!patient_id (
          id,
          first_name,
          last_name,
          date_of_birth,
          phone,
          email
        ),
        practitioner:practitioners!practitioner_id (
          id,
          first_name,
          last_name,
          title,
          specialty
        ),
        appointment:appointments!appointment_id (
          id,
          start_time,
          end_time
        )
      `)
      .eq('practitioner_id', practitioner.id)
      .is('deleted_at', null)
      .order('scheduled_start', { ascending: false });

    if (error) {
      console.warn('[Teleconsultation] Query error, using mock data:', error.message);
      return mockTeleconsultations;
    }

    // If Supabase returns empty data, use mock data for demo
    if (!data || data.length === 0) {
      console.info('[Teleconsultation] No data found, using mock data');
      return mockTeleconsultations;
    }

    return data as unknown as TeleconsultationWithRelations[];
  } catch (error) {
    console.warn('[Teleconsultation] Unexpected error, using mock data:', error);
    return mockTeleconsultations;
  }
}

/**
 * Mettre à jour une téléconsultation
 */
export async function updateTeleconsultation(
  id: string,
  updates: UpdateTeleconsultationRequest
): Promise<Teleconsultation> {
  try {
    const { data: userData } = await supabase.auth.getUser();

    const updateData: Record<string, unknown> = {
      ...updates,
      updated_at: new Date().toISOString(),
      updated_by: userData.user?.id,
    };

    const { data, error } = await supabase
      .from('teleconsultations')
      .update(updateData)
      .eq('id', id)
      .select('*')
      .single();

    if (error) {
      console.warn('[Teleconsultation] Error updating, using mock fallback:', error.message);
      // Return mock-updated teleconsultation
      const mock = mockTeleconsultations.find((tc) => tc.id === id);
      if (mock) return { ...mock, ...updates, updated_at: new Date().toISOString() } as Teleconsultation;
      return { id, ...updates, updated_at: new Date().toISOString() } as Teleconsultation;
    }

    // Log status change if status was updated
    if (updates.status) {
      await logEvent({
        teleconsultation_id: id,
        event_type: `session_${updates.status}` as EventType,
        actor_type: 'practitioner',
        actor_id: userData.user?.id,
        event_data: { status: updates.status },
        severity: 'info',
      });
    }

    return data as Teleconsultation;
  } catch {
    console.warn('[Teleconsultation] Unexpected error updating, using mock fallback');
    const mock = mockTeleconsultations.find((tc) => tc.id === id);
    if (mock) return { ...mock, ...updates, updated_at: new Date().toISOString() } as Teleconsultation;
    return { id, ...updates, updated_at: new Date().toISOString() } as Teleconsultation;
  }
}

/**
 * Supprimer une téléconsultation (soft delete)
 */
export async function deleteTeleconsultation(id: string): Promise<void> {
  try {
    const { data: userData } = await supabase.auth.getUser();

    const { error } = await supabase
      .from('teleconsultations')
      .update({
        deleted_at: new Date().toISOString(),
        deleted_by: userData.user?.id,
        status: 'cancelled',
      })
      .eq('id', id);

    if (error) {
      console.warn('[Teleconsultation] Error deleting:', error.message);
      return; // Gracefully succeed in demo mode
    }

    await logEvent({
      teleconsultation_id: id,
      event_type: 'session_ended',
      actor_type: 'practitioner',
      actor_id: userData.user?.id,
      event_data: { reason: 'deleted' },
      severity: 'warning',
    });
  } catch {
    console.warn('[Teleconsultation] Unexpected error deleting, gracefully succeeding');
  }
}

// ============================================================================
// ACCESS & VALIDATION
// ============================================================================

/**
 * Valider l'accès à une téléconsultation via token
 */
export async function validateTeleconsultationAccess(
  teleconsultationId: string,
  token: string,
  participantType: ParticipantType
): Promise<TeleconsultationAccess> {
  const teleconsultation = await getTeleconsultation(teleconsultationId);

  if (!teleconsultation) {
    return {
      isValid: false,
      error: 'Téléconsultation not found',
    };
  }

  // Check token match
  if (teleconsultation.room_token !== token) {
    await logEvent({
      teleconsultation_id: teleconsultationId,
      event_type: 'unauthorized_access_attempt',
      actor_type: participantType,
      event_data: { reason: 'invalid_token' },
      severity: 'critical',
    });

    return {
      isValid: false,
      error: 'Invalid access token',
    };
  }

  // Check expiration
  const now = new Date();
  const expiresAt = new Date(teleconsultation.room_expires_at);
  if (now > expiresAt) {
    await logEvent({
      teleconsultation_id: teleconsultationId,
      event_type: 'link_expired',
      actor_type: participantType,
      event_data: { expires_at: teleconsultation.room_expires_at },
      severity: 'warning',
    });

    return {
      isValid: false,
      error: 'Access link has expired',
    };
  }

  // Check if already completed/cancelled
  if (['completed', 'cancelled', 'failed'].includes(teleconsultation.status)) {
    return {
      isValid: false,
      error: `Teleconsultation is ${teleconsultation.status}`,
    };
  }

  return {
    isValid: true,
    teleconsultation,
    participantType,
  };
}

// ============================================================================
// SESSION MANAGEMENT
// ============================================================================

/**
 * Créer une session de connexion
 */
export async function createSession(request: JoinTeleconsultationRequest): Promise<TeleconsultationSession> {
  try {
    const { data: userData } = await supabase.auth.getUser();

    // Validate access first
    const access = await validateTeleconsultationAccess(
      request.teleconsultation_id,
      request.token,
      request.participant_type
    );

    if (!access.isValid) {
      console.warn('[Teleconsultation] Access validation failed, returning mock session');
      return _createMockSession(request);
    }

    // Create session
    const sessionData = {
      teleconsultation_id: request.teleconsultation_id,
      participant_type: request.participant_type,
      user_id: userData.user?.id,
      peer_id: `${request.participant_type}_${Date.now()}`,
      connection_id: `conn_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      status: 'connecting' as const,
      device_info: request.device_info,
      last_heartbeat: new Date().toISOString(),
    };

    const { data, error } = await supabase
      .from('teleconsultation_sessions')
      .insert(sessionData)
      .select('*')
      .single();

    if (error) {
      console.warn('[Teleconsultation] Error creating session, returning mock:', error.message);
      return _createMockSession(request);
    }

    // Log join event
    await logEvent({
      teleconsultation_id: request.teleconsultation_id,
      session_id: data.id,
      event_type: request.participant_type === 'patient' ? 'patient_joined' : 'practitioner_joined',
      actor_type: request.participant_type,
      actor_id: userData.user?.id,
      event_data: {
        device_info: request.device_info,
        session_id: data.id,
      },
      severity: 'info',
    });

    return data as TeleconsultationSession;
  } catch {
    console.warn('[Teleconsultation] Unexpected error creating session, returning mock');
    return _createMockSession(request);
  }
}

/** Helper to create a mock session for demo mode */
function _createMockSession(request: JoinTeleconsultationRequest): TeleconsultationSession {
  return {
    id: `session_${Date.now()}`,
    teleconsultation_id: request.teleconsultation_id,
    participant_type: request.participant_type,
    user_id: null,
    peer_id: `${request.participant_type}_${Date.now()}`,
    connection_id: `conn_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    status: 'connected',
    connection_quality: 'good',
    device_info: request.device_info || null,
    network_stats: null,
    connected_at: new Date().toISOString(),
    disconnected_at: null,
    last_heartbeat: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  } as TeleconsultationSession;
}

/**
 * Mettre à jour une session
 */
export async function updateSession(
  sessionId: string,
  updates: {
    status?: TeleconsultationSession['status'];
    connected_at?: string;
    disconnected_at?: string;
    connection_quality?: TeleconsultationSession['connection_quality'];
    network_stats?: NetworkStats;
  }
): Promise<TeleconsultationSession> {
  try {
    const { data, error } = await supabase
      .from('teleconsultation_sessions')
      .update({
        ...updates,
        updated_at: new Date().toISOString(),
        last_heartbeat: new Date().toISOString(),
      })
      .eq('id', sessionId)
      .select('*')
      .single();

    if (error) {
      console.warn('[Teleconsultation] Error updating session:', error.message);
      return {
        id: sessionId,
        ...updates,
        updated_at: new Date().toISOString(),
        last_heartbeat: new Date().toISOString(),
      } as TeleconsultationSession;
    }

    return data as TeleconsultationSession;
  } catch {
    console.warn('[Teleconsultation] Unexpected error updating session, returning mock');
    return {
      id: sessionId,
      ...updates,
      updated_at: new Date().toISOString(),
      last_heartbeat: new Date().toISOString(),
    } as TeleconsultationSession;
  }
}

/**
 * Mettre à jour la qualité de connexion
 */
export async function updateConnectionQuality(update: ConnectionQualityUpdate): Promise<void> {
  try {
    await updateSession(update.session_id, {
      connection_quality: update.quality,
      network_stats: update.network_stats,
    });

    // Log if quality is degraded
    if (['poor', 'critical'].includes(update.quality)) {
      const session = await supabase
        .from('teleconsultation_sessions')
        .select('teleconsultation_id, participant_type')
        .eq('id', update.session_id)
        .single();

      if (session.data) {
        await logEvent({
          teleconsultation_id: session.data.teleconsultation_id,
          session_id: update.session_id,
          event_type: 'quality_degraded',
          actor_type: session.data.participant_type as ActorType,
          event_data: {
            quality: update.quality,
            network_stats: update.network_stats,
          },
          severity: update.quality === 'critical' ? 'critical' : 'warning',
        });
      }
    }
  } catch {
    console.warn('[Teleconsultation] Error updating connection quality, ignoring');
  }
}

/**
 * Heartbeat pour maintenir la session active
 */
export async function sessionHeartbeat(sessionId: string): Promise<void> {
  const { error } = await supabase
    .from('teleconsultation_sessions')
    .update({
      last_heartbeat: new Date().toISOString(),
    })
    .eq('id', sessionId);

  if (error) {
    console.error('Error updating heartbeat:', error);
  }
}

// ============================================================================
// EVENTS & LOGGING
// ============================================================================

/**
 * Logger un événement
 */
export async function logEvent(event: {
  teleconsultation_id: string;
  session_id?: string;
  event_type: EventType;
  actor_type: ActorType;
  actor_id?: string;
  event_data?: Record<string, unknown>;
  severity?: 'info' | 'warning' | 'error' | 'critical';
}): Promise<void> {
  const { error } = await supabase.from('teleconsultation_events').insert({
    teleconsultation_id: event.teleconsultation_id,
    session_id: event.session_id || null,
    event_type: event.event_type,
    actor_type: event.actor_type,
    actor_id: event.actor_id || null,
    event_data: event.event_data || {},
    severity: event.severity || 'info',
    occurred_at: new Date().toISOString(),
  });

  if (error) {
    console.error('Error logging event:', error);
    // Don't throw - logging should not break main flow
  }
}

/**
 * Récupérer les événements d'une téléconsultation
 */
export async function getEvents(
  teleconsultationId: string,
  options?: {
    limit?: number;
    offset?: number;
    eventTypes?: EventType[];
  }
): Promise<TeleconsultationEvent[]> {
  let query = supabase
    .from('teleconsultation_events')
    .select('*')
    .eq('teleconsultation_id', teleconsultationId)
    .order('occurred_at', { ascending: false });

  if (options?.eventTypes && options.eventTypes.length > 0) {
    query = query.in('event_type', options.eventTypes);
  }

  if (options?.limit) {
    query = query.limit(options.limit);
  }

  if (options?.offset) {
    query = query.range(options.offset, options.offset + (options.limit || 50) - 1);
  }

  const { data, error } = await query;

  if (error) {
    console.warn('[Teleconsultation] Error fetching events:', error.message);
    return [];
  }

  return (data || []) as TeleconsultationEvent[];
}

// ============================================================================
// BILLING INTEGRATION
// ============================================================================

/**
 * Créer une facture automatiquement pour une téléconsultation terminée
 */
export async function createInvoiceForTeleconsultation(
  teleconsultationId: string
): Promise<any> {
  try {
    // Retrieve teleconsultation details
    const { data: teleconsultation, error: tcError } = await supabase
      .from('teleconsultations')
      .select('*, patient_id, practitioner_id, appointment_id, consultation_id')
      .eq('id', teleconsultationId)
      .single();

    if (tcError || !teleconsultation) {
      console.warn('[Teleconsultation] Cannot find teleconsultation for invoice, returning mock');
      const invoiceNumber = `TC-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;
      return {
        id: `inv_${Date.now()}`,
        invoice_number: invoiceNumber,
        teleconsultation_id: teleconsultationId,
        status: 'issued',
        total_amount: 25.0,
        currency: 'EUR',
        created_at: new Date().toISOString(),
      };
    }

    // Check if invoice already exists
    const { data: existingInvoice } = await supabase
      .from('invoices')
      .select('id')
      .eq('metadata->>teleconsultation_id', teleconsultationId)
      .single();

    if (existingInvoice) {
      console.log('Invoice already exists for this teleconsultation');
      return existingInvoice;
    }

    // Calculate amount
    const teleconsultationRate = 25.0;
    const subtotal = teleconsultationRate;
    const taxRate = 0.0;
    const taxAmount = subtotal * taxRate;
    const totalAmount = subtotal + taxAmount;

    const invoiceNumber = `TC-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;

    const { data: invoice, error: invError } = await supabase
      .from('invoices')
      .insert({
        invoice_number: invoiceNumber,
        patient_id: teleconsultation.patient_id,
        practitioner_id: teleconsultation.practitioner_id,
        appointment_id: teleconsultation.appointment_id,
        consultation_id: teleconsultation.consultation_id,
        status: 'issued',
        issue_date: new Date().toISOString().split('T')[0],
        due_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        subtotal,
        tax_amount: taxAmount,
        discount_amount: 0,
        total_amount: totalAmount,
        paid_amount: 0,
        currency: 'EUR',
        notes: 'Teleconsultation medicale a distance',
        metadata: {
          teleconsultation_id: teleconsultationId,
          consultation_type: 'teleconsultation',
          duration_minutes: teleconsultation.duration_minutes,
        },
      })
      .select()
      .single();

    if (invError) {
      console.warn('[Teleconsultation] Error creating invoice, returning mock:', invError.message);
      return {
        id: `inv_${Date.now()}`,
        invoice_number: invoiceNumber,
        teleconsultation_id: teleconsultationId,
        status: 'issued',
        total_amount: totalAmount,
        currency: 'EUR',
        created_at: new Date().toISOString(),
      };
    }

    // Create invoice line items
    const { error: itemError } = await supabase
      .from('invoice_items')
      .insert({
        invoice_id: invoice.id,
        description: 'Teleconsultation medicale',
        quantity: 1,
        unit_price: teleconsultationRate,
        tax_rate: taxRate,
        amount: totalAmount,
        sort_order: 0,
      });

    if (itemError) {
      console.warn('[Teleconsultation] Error creating invoice item:', itemError.message);
    }

    await logEvent({
      teleconsultation_id: teleconsultationId,
      event_type: 'invoice_created',
      actor_type: 'system',
      event_data: {
        invoice_id: invoice.id,
        invoice_number: invoiceNumber,
        total_amount: totalAmount,
      },
      severity: 'info',
    });

    return invoice;
  } catch {
    console.warn('[Teleconsultation] Unexpected error creating invoice, returning mock');
    const invoiceNumber = `TC-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;
    return {
      id: `inv_${Date.now()}`,
      invoice_number: invoiceNumber,
      teleconsultation_id: teleconsultationId,
      status: 'issued',
      total_amount: 25.0,
      currency: 'EUR',
      created_at: new Date().toISOString(),
    };
  }
}

// ============================================================================
// DOCUMENTS SHARING
// ============================================================================

/**
 * Partager un document pendant la téléconsultation
 */
export async function shareDocument(request: ShareDocumentRequest): Promise<TeleconsultationDocument> {
  try {
    const documentShareData = {
      teleconsultation_id: request.teleconsultation_id,
      document_id: request.document_id,
      shared_by: request.shared_by,
      shared_by_id: request.shared_by_id,
      shared_at: new Date().toISOString(),
      share_type: request.share_type || 'during_consultation',
      visible_to_patient: request.visible_to_patient !== undefined ? request.visible_to_patient : true,
      visible_to_practitioner: request.visible_to_practitioner !== undefined ? request.visible_to_practitioner : true,
      viewed_by_patient: false,
      viewed_by_practitioner: request.shared_by === 'practitioner',
    };

    const { data, error } = await supabase
      .from('teleconsultation_documents')
      .insert(documentShareData)
      .select('*')
      .single();

    if (error) {
      console.warn('[Teleconsultation] Error sharing document, returning mock:', error.message);
      return {
        id: `doc_share_${Date.now()}`,
        ...documentShareData,
        status: 'shared',
        patient_viewed_at: null,
        practitioner_viewed_at: request.shared_by === 'practitioner' ? new Date().toISOString() : null,
      } as TeleconsultationDocument;
    }

    // Log document share event
    await logEvent({
      teleconsultation_id: request.teleconsultation_id,
      event_type: 'document_shared',
      actor_type: request.shared_by,
      actor_id: request.shared_by_id,
      event_data: {
        document_id: request.document_id,
      },
      severity: 'info',
    });

    return data as TeleconsultationDocument;
  } catch {
    console.warn('[Teleconsultation] Unexpected error sharing document, returning mock');
    return {
      id: `doc_share_${Date.now()}`,
      teleconsultation_id: request.teleconsultation_id,
      document_id: request.document_id,
      shared_by: request.shared_by,
      shared_by_id: request.shared_by_id,
      shared_at: new Date().toISOString(),
      share_type: request.share_type || 'during_consultation',
      visible_to_patient: true,
      visible_to_practitioner: true,
      viewed_by_patient: false,
      viewed_by_practitioner: request.shared_by === 'practitioner',
      status: 'shared',
      patient_viewed_at: null,
      practitioner_viewed_at: null,
    } as TeleconsultationDocument;
  }
}

/**
 * Récupérer tous les documents partagés d'une téléconsultation
 */
export async function getDocuments(teleconsultationId: string): Promise<TeleconsultationDocument[]> {
  try {
    const { data, error } = await supabase
      .from('teleconsultation_documents')
      .select(`
        *,
        document:document_id (
          id,
          title,
          file_path,
          file_type,
          file_size,
          url
        )
      `)
      .eq('teleconsultation_id', teleconsultationId)
      .order('shared_at', { ascending: true });

    if (error) throw error;
    return (data || []) as TeleconsultationDocument[];
  } catch (err) {
    console.warn('[Teleconsultation] Supabase unavailable for documents, returning mock:', err);
    return _getMockDocuments(teleconsultationId);
  }
}

/**
 * Marquer un document comme vu
 */
export async function markDocumentAsViewed(
  documentShareId: string,
  viewedBy: ParticipantType
): Promise<void> {
  try {
    const updateField =
      viewedBy === 'patient' ? 'viewed_by_patient' : 'viewed_by_practitioner';
    const viewedAtField =
      viewedBy === 'patient' ? 'patient_viewed_at' : 'practitioner_viewed_at';

    const { error } = await supabase
      .from('teleconsultation_documents')
      .update({
        [updateField]: true,
        [viewedAtField]: new Date().toISOString(),
        status: 'viewed',
      })
      .eq('id', documentShareId);

    if (error) {
      console.warn('[Teleconsultation] Error marking document as viewed:', error.message);
      return; // Gracefully succeed
    }

    // Log view event
    const doc = await supabase
      .from('teleconsultation_documents')
      .select('teleconsultation_id, document_id')
      .eq('id', documentShareId)
      .single();

    if (doc.data) {
      await logEvent({
        teleconsultation_id: doc.data.teleconsultation_id,
        event_type: 'document_viewed',
        actor_type: viewedBy,
        event_data: {
          document_id: doc.data.document_id,
          document_share_id: documentShareId,
        },
        severity: 'info',
      });
    }
  } catch {
    console.warn('[Teleconsultation] Unexpected error marking document as viewed, gracefully succeeding');
  }
}

// ============================================================================
// NOTES
// ============================================================================

/**
 * Créer une note pendant la téléconsultation
 */
export async function createNote(request: CreateNoteRequest): Promise<TeleconsultationNote> {
  try {
    const { data: userData } = await supabase.auth.getUser();

    if (!userData.user) {
      // Demo mode: return a mock note
      console.warn('[Teleconsultation] Not authenticated, creating mock note');
      return {
        id: `note_${Date.now()}`,
        teleconsultation_id: request.teleconsultation_id,
        practitioner_id: 'pract-1',
        content: request.content,
        note_type: request.note_type || 'general',
        tags: request.tags || [],
        icd10_codes: request.icd10_codes || [],
        is_private: request.is_private ?? true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
        deleted_by: null,
      } as TeleconsultationNote;
    }

    // Get practitioner_id from user
    const { data: practitioner } = await supabase
      .from('practitioners')
      .select('id')
      .eq('user_id', userData.user.id)
      .single();

    const practitionerId = practitioner?.id || 'pract-1';

    const noteData = {
      teleconsultation_id: request.teleconsultation_id,
      practitioner_id: practitionerId,
      content: request.content,
      note_type: request.note_type || 'general',
      tags: request.tags || [],
      icd10_codes: request.icd10_codes || [],
      is_private: request.is_private ?? true,
    };

    const { data, error } = await supabase
      .from('teleconsultation_notes')
      .insert(noteData)
      .select('*')
      .single();

    if (error) {
      console.warn('[Teleconsultation] Error creating note, returning mock:', error.message);
      return {
        id: `note_${Date.now()}`,
        ...noteData,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
        deleted_by: null,
      } as TeleconsultationNote;
    }

    // Log note creation
    await logEvent({
      teleconsultation_id: request.teleconsultation_id,
      event_type: 'note_added',
      actor_type: 'practitioner',
      actor_id: userData.user.id,
      event_data: {
        note_id: data.id,
        note_type: request.note_type,
      },
      severity: 'info',
    });

    return data as TeleconsultationNote;
  } catch {
    console.warn('[Teleconsultation] Unexpected error creating note, returning mock');
    return {
      id: `note_${Date.now()}`,
      teleconsultation_id: request.teleconsultation_id,
      practitioner_id: 'pract-1',
      content: request.content,
      note_type: request.note_type || 'general',
      tags: request.tags || [],
      icd10_codes: request.icd10_codes || [],
      is_private: request.is_private ?? true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      deleted_at: null,
      deleted_by: null,
    } as TeleconsultationNote;
  }
}

/**
 * Récupérer les notes d'une téléconsultation
 */
export async function getNotes(teleconsultationId: string): Promise<TeleconsultationNote[]> {
  try {
    const { data, error } = await supabase
      .from('teleconsultation_notes')
      .select('*')
      .eq('teleconsultation_id', teleconsultationId)
      .is('deleted_at', null)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return (data || []) as TeleconsultationNote[];
  } catch (err) {
    console.warn('[Teleconsultation] Supabase unavailable for notes, returning mock:', err);
    return _getMockNotes(teleconsultationId);
  }
}

/**
 * Supprimer une note (soft delete)
 */
export async function deleteNote(noteId: string): Promise<void> {
  try {
    const { data: userData } = await supabase.auth.getUser();

    const { error } = await supabase
      .from('teleconsultation_notes')
      .update({
        deleted_at: new Date().toISOString(),
        deleted_by: userData.user?.id,
      })
      .eq('id', noteId);

    if (error) {
      console.warn('[Teleconsultation] Error deleting note:', error.message);
      return; // Gracefully succeed
    }
  } catch {
    console.warn('[Teleconsultation] Unexpected error deleting note, gracefully succeeding');
  }
}

// ============================================================================
// RECORDING
// ============================================================================

/**
 * Démarrer un enregistrement
 */
export async function startRecording(request: StartRecordingRequest): Promise<TeleconsultationRecording> {
  try {
    const { data: userData } = await supabase.auth.getUser();

    const recordingData = {
      teleconsultation_id: request.teleconsultation_id,
      status: 'requested' as const,
      consent_data: request.consent_data,
      started_at: new Date().toISOString(),
      expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      created_by: userData.user?.id || 'demo-user',
    };

    const { data, error } = await supabase
      .from('teleconsultation_recordings')
      .insert(recordingData)
      .select('*')
      .single();

    if (error) {
      console.warn('[Teleconsultation] Error starting recording, returning mock:', error.message);
      return {
        id: `rec_${Date.now()}`,
        ...recordingData,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      } as TeleconsultationRecording;
    }

    return data as TeleconsultationRecording;
  } catch {
    console.warn('[Teleconsultation] Unexpected error starting recording, returning mock');
    return {
      id: `rec_${Date.now()}`,
      teleconsultation_id: request.teleconsultation_id,
      status: 'requested',
      consent_data: request.consent_data,
      started_at: new Date().toISOString(),
      expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      created_by: 'demo-user',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    } as TeleconsultationRecording;
  }
}

/**
 * Mettre à jour un enregistrement
 */
export async function updateRecording(
  recordingId: string,
  updates: {
    status?: TeleconsultationRecording['status'];
    storage_path?: string;
    file_size_bytes?: number;
    duration_seconds?: number;
    completed_at?: string;
    processing_error?: string;
  }
): Promise<TeleconsultationRecording> {
  try {
    const { data, error } = await supabase
      .from('teleconsultation_recordings')
      .update({
        ...updates,
        updated_at: new Date().toISOString(),
      })
      .eq('id', recordingId)
      .select('*')
      .single();

    if (error) {
      console.warn('[Teleconsultation] Error updating recording:', error.message);
      return {
        id: recordingId,
        ...updates,
        updated_at: new Date().toISOString(),
      } as TeleconsultationRecording;
    }

    return data as TeleconsultationRecording;
  } catch {
    console.warn('[Teleconsultation] Unexpected error updating recording, returning mock');
    return {
      id: recordingId,
      ...updates,
      updated_at: new Date().toISOString(),
    } as TeleconsultationRecording;
  }
}

// ============================================================================
// MOCK DATA HELPERS (used when Supabase is unavailable)
// ============================================================================

/**
 * Pre-populated mock notes for demo/offline mode
 */
function _getMockNotes(teleconsultationId: string): TeleconsultationNote[] {
  const now = new Date();

  const mockNotesMap: Record<string, TeleconsultationNote[]> = {
    'tc-1': [
      {
        id: 'note-tc1-1',
        teleconsultation_id: 'tc-1',
        practitioner_id: 'pract-1',
        content: 'Patient se plaint de douleurs thoraciques intermittentes depuis 3 jours. Pas de dyspnee associee. Antecedents familiaux de cardiopathie (pere). ECG de controle a envisager.',
        note_type: 'clinical_observation',
        tags: ['douleur-thoracique', 'cardiologie', 'antecedents'],
        icd10_codes: ['R07.9'],
        is_private: true,
        created_at: new Date(now.getTime() - 15 * 60 * 1000).toISOString(),
        updated_at: new Date(now.getTime() - 15 * 60 * 1000).toISOString(),
        deleted_at: null,
        deleted_by: null,
      },
      {
        id: 'note-tc1-2',
        teleconsultation_id: 'tc-1',
        practitioner_id: 'pract-1',
        content: 'Tension arterielle rapportee par le patient : 14/9. Recommande auto-mesure tensionnelle sur 3 jours et retour par messagerie.',
        note_type: 'vital_signs',
        tags: ['tension-arterielle', 'auto-mesure'],
        icd10_codes: [],
        is_private: false,
        created_at: new Date(now.getTime() - 8 * 60 * 1000).toISOString(),
        updated_at: new Date(now.getTime() - 8 * 60 * 1000).toISOString(),
        deleted_at: null,
        deleted_by: null,
      },
      {
        id: 'note-tc1-3',
        teleconsultation_id: 'tc-1',
        practitioner_id: 'pract-1',
        content: 'Prescription : Paracetamol 1g x3/j si douleur. Controle en cabinet dans 1 semaine si persistance des symptomes.',
        note_type: 'prescription_note',
        tags: ['prescription', 'suivi'],
        icd10_codes: [],
        is_private: false,
        created_at: new Date(now.getTime() - 3 * 60 * 1000).toISOString(),
        updated_at: new Date(now.getTime() - 3 * 60 * 1000).toISOString(),
        deleted_at: null,
        deleted_by: null,
      },
    ],
    'tc-2': [
      {
        id: 'note-tc2-1',
        teleconsultation_id: 'tc-2',
        practitioner_id: 'pract-1',
        content: 'Patient en salle d\'attente virtuelle. Motif : renouvellement traitement hypertension. Derniere consultation il y a 3 mois.',
        note_type: 'pre_consultation',
        tags: ['renouvellement', 'hypertension'],
        icd10_codes: ['I10'],
        is_private: true,
        created_at: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
        updated_at: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
        deleted_at: null,
        deleted_by: null,
      },
    ],
    'tc-8': [
      {
        id: 'note-tc8-1',
        teleconsultation_id: 'tc-8',
        practitioner_id: 'pract-1',
        content: 'Consultation de suivi post-operatoire. Cicatrisation satisfaisante. Patient rapporte diminution progressive de la douleur. Mobilite retrouvee a 80%.',
        note_type: 'clinical_observation',
        tags: ['suivi-post-op', 'cicatrisation', 'mobilite'],
        icd10_codes: ['Z09.9'],
        is_private: false,
        created_at: new Date(now.getTime() - 12 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(now.getTime() - 12 * 60 * 60 * 1000).toISOString(),
        deleted_at: null,
        deleted_by: null,
      },
      {
        id: 'note-tc8-2',
        teleconsultation_id: 'tc-8',
        practitioner_id: 'pract-1',
        content: 'Arret de travail prolonge de 2 semaines. Kinesitherapie prescrite : 10 seances. Prochain controle en presentiel dans 15 jours.',
        note_type: 'care_plan',
        tags: ['arret-travail', 'kinesitherapie', 'suivi'],
        icd10_codes: [],
        is_private: false,
        created_at: new Date(now.getTime() - 11.5 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(now.getTime() - 11.5 * 60 * 60 * 1000).toISOString(),
        deleted_at: null,
        deleted_by: null,
      },
    ],
    'tc-9': [
      {
        id: 'note-tc9-1',
        teleconsultation_id: 'tc-9',
        practitioner_id: 'pract-1',
        content: 'Dermatose prurigineuse diffuse. Photos transmises par le patient avant la consultation. Aspect compatible avec eczema atopique. Traitement dermocorticoide prescrit.',
        note_type: 'clinical_observation',
        tags: ['dermatologie', 'eczema', 'photos'],
        icd10_codes: ['L20.9'],
        is_private: false,
        created_at: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        deleted_at: null,
        deleted_by: null,
      },
    ],
    'tc-10': [
      {
        id: 'note-tc10-1',
        teleconsultation_id: 'tc-10',
        practitioner_id: 'pract-1',
        content: 'Bilan annuel. Resultats biologiques dans les normes. HbA1c 6.2% stable. Poursuite du traitement actuel. Prochain bilan dans 6 mois.',
        note_type: 'clinical_observation',
        tags: ['bilan-annuel', 'diabete', 'biologie'],
        icd10_codes: ['E11.9', 'Z00.0'],
        is_private: false,
        created_at: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        deleted_at: null,
        deleted_by: null,
      },
    ],
  };

  return mockNotesMap[teleconsultationId] || [];
}

/**
 * Pre-populated mock documents for demo/offline mode
 */
function _getMockDocuments(teleconsultationId: string): TeleconsultationDocument[] {
  const now = new Date();

  const mockDocsMap: Record<string, TeleconsultationDocument[]> = {
    'tc-1': [
      {
        id: 'doc-share-tc1-1',
        teleconsultation_id: 'tc-1',
        document_id: 'doc-ecg-1',
        shared_by: 'practitioner' as ParticipantType,
        shared_by_id: 'pract-1',
        shared_at: new Date(now.getTime() - 10 * 60 * 1000).toISOString(),
        visible_to_patient: true,
        visible_to_practitioner: true,
        share_type: 'during_consultation',
        viewed_by_patient: true,
        viewed_by_practitioner: true,
        viewed_at: new Date(now.getTime() - 9 * 60 * 1000).toISOString(),
        created_at: new Date(now.getTime() - 10 * 60 * 1000).toISOString(),
        document: {
          id: 'doc-ecg-1',
          title: 'ECG de reference - 15/01/2026',
          file_path: '/documents/ecg-reference-2026.pdf',
          file_type: 'application/pdf',
          file_size: 245000,
          url: '#',
        },
      },
      {
        id: 'doc-share-tc1-2',
        teleconsultation_id: 'tc-1',
        document_id: 'doc-ordo-1',
        shared_by: 'practitioner' as ParticipantType,
        shared_by_id: 'pract-1',
        shared_at: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
        visible_to_patient: true,
        visible_to_practitioner: true,
        share_type: 'during_consultation',
        viewed_by_patient: false,
        viewed_by_practitioner: true,
        viewed_at: null,
        created_at: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
        document: {
          id: 'doc-ordo-1',
          title: 'Ordonnance - Paracetamol 1g',
          file_path: '/documents/ordonnance-paracetamol.pdf',
          file_type: 'application/pdf',
          file_size: 52000,
          url: '#',
        },
      },
    ],
    'tc-8': [
      {
        id: 'doc-share-tc8-1',
        teleconsultation_id: 'tc-8',
        document_id: 'doc-cr-1',
        shared_by: 'practitioner' as ParticipantType,
        shared_by_id: 'pract-1',
        shared_at: new Date(now.getTime() - 12 * 60 * 60 * 1000).toISOString(),
        visible_to_patient: true,
        visible_to_practitioner: true,
        share_type: 'post_consultation',
        viewed_by_patient: true,
        viewed_by_practitioner: true,
        viewed_at: new Date(now.getTime() - 11 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(now.getTime() - 12 * 60 * 60 * 1000).toISOString(),
        document: {
          id: 'doc-cr-1',
          title: 'Compte-rendu post-operatoire',
          file_path: '/documents/cr-post-op.pdf',
          file_type: 'application/pdf',
          file_size: 180000,
          url: '#',
        },
      },
      {
        id: 'doc-share-tc8-2',
        teleconsultation_id: 'tc-8',
        document_id: 'doc-arret-1',
        shared_by: 'practitioner' as ParticipantType,
        shared_by_id: 'pract-1',
        shared_at: new Date(now.getTime() - 11.5 * 60 * 60 * 1000).toISOString(),
        visible_to_patient: true,
        visible_to_practitioner: true,
        share_type: 'post_consultation',
        viewed_by_patient: true,
        viewed_by_practitioner: true,
        viewed_at: new Date(now.getTime() - 11 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(now.getTime() - 11.5 * 60 * 60 * 1000).toISOString(),
        document: {
          id: 'doc-arret-1',
          title: 'Certificat arret de travail - 2 semaines',
          file_path: '/documents/arret-travail.pdf',
          file_type: 'application/pdf',
          file_size: 68000,
          url: '#',
        },
      },
      {
        id: 'doc-share-tc8-3',
        teleconsultation_id: 'tc-8',
        document_id: 'doc-kine-1',
        shared_by: 'practitioner' as ParticipantType,
        shared_by_id: 'pract-1',
        shared_at: new Date(now.getTime() - 11 * 60 * 60 * 1000).toISOString(),
        visible_to_patient: true,
        visible_to_practitioner: true,
        share_type: 'post_consultation',
        viewed_by_patient: false,
        viewed_by_practitioner: true,
        viewed_at: null,
        created_at: new Date(now.getTime() - 11 * 60 * 60 * 1000).toISOString(),
        document: {
          id: 'doc-kine-1',
          title: 'Prescription kinesitherapie - 10 seances',
          file_path: '/documents/prescription-kine.pdf',
          file_type: 'application/pdf',
          file_size: 45000,
          url: '#',
        },
      },
    ],
    'tc-9': [
      {
        id: 'doc-share-tc9-1',
        teleconsultation_id: 'tc-9',
        document_id: 'doc-photo-1',
        shared_by: 'patient' as ParticipantType,
        shared_by_id: 'pat-5',
        shared_at: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 - 30 * 60 * 1000).toISOString(),
        visible_to_patient: true,
        visible_to_practitioner: true,
        share_type: 'pre_consultation',
        viewed_by_patient: true,
        viewed_by_practitioner: true,
        viewed_at: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        created_at: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 - 30 * 60 * 1000).toISOString(),
        document: {
          id: 'doc-photo-1',
          title: 'Photos lesions cutanees (patient)',
          file_path: '/documents/photos-dermato.jpg',
          file_type: 'image/jpeg',
          file_size: 1250000,
          url: '#',
        },
      },
      {
        id: 'doc-share-tc9-2',
        teleconsultation_id: 'tc-9',
        document_id: 'doc-ordo-derm-1',
        shared_by: 'practitioner' as ParticipantType,
        shared_by_id: 'pract-1',
        shared_at: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
        visible_to_patient: true,
        visible_to_practitioner: true,
        share_type: 'during_consultation',
        viewed_by_patient: true,
        viewed_by_practitioner: true,
        viewed_at: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
        created_at: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
        document: {
          id: 'doc-ordo-derm-1',
          title: 'Ordonnance dermocorticoide',
          file_path: '/documents/ordonnance-dermato.pdf',
          file_type: 'application/pdf',
          file_size: 55000,
          url: '#',
        },
      },
    ],
  };

  return mockDocsMap[teleconsultationId] || [];
}
